'use strict';


export const FETCH_DEPARTMENT_DATA_SUCCESS = 'FETCH_DEPARTMENT_DATA_SUCCESS';
export const FETCH_DEPARTMENT_DATA_FAILURE = 'FETCH_DEPARTMENT_DATA_FAILURE';
export const FETCH_DEPARTMENT_DATE_REQUEST = 'FETCH_DEPARTMENT_DATE_REQUEST';

export const FETCH_SUB_CATEGORIES_DATA_SUCCESS = 'FETCH_SUB_CATEGORIES_DATA_SUCCESS';
export const FETCH_SUB_CATEGORIES_DATA_FAILURE = 'FETCH_SUB_CATEGORIES_DATA_FAILURE';
export const FETCH_SUB_CATEGORIES_DATE_REQUEST = 'FETCH_SUB_CATEGORIES_DATE_REQUEST';

export const FETCH_PLP_DATA_SUCCESS = 'FETCH_PLP_DATA_SUCCESS';
export const FETCH_PLP_DATA_FAILURE = 'FETCH_PLP_DATA_FAILURE';
export const FETCH_PLP_DATE_REQUEST = 'FETCH_PLP_DATE_REQUEST';

export const FETCH_PDP_DATA_SUCCESS = 'FETCH_PDP_DATA_SUCCESS';
export const FETCH_PDP_DATA_FAILURE = 'FETCH_PDP_DATA_FAILURE';
export const FETCH_PDP_DATE_REQUEST = 'FETCH_PDP_DATE_REQUEST';